# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/report-server"

# KB portal info
has_kb_portal: true

# CTA Panel info
has_cta_panels: true

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock,api_sort.rb,build_kb.rb,switch-ruby.cmd]
exclude_navigation: [knowledge-base/*]
navigation:
## List your directory names and order here, like this:
    user-guide:
        position: 110
        title: "User Guide"
    implementer-guide:
        position: 120
        title: "Implementer Guide"
    implementer-guide/licensing-and-distribution:
        position: 130
        title: "Licensing and Distribution"    
    implementer-guide/setup:
        position: 200
        title: "Setup"    
    implementer-guide/user-management:
        position: 210
        title: "User Management"    
    implementer-guide/configuration:
        position: 220
        title: "Configuration Page"  
    user-guide/reports-management:
        position: 400
        title: "Reports Management" 
    implementer-guide/connecting-to-data:
        position: 600
        title: "Connecting to Data" 
    implementer-guide/apis:
        position: 10000
        title: "APIs"      
    implementer-guide/apis/rest-api:
        position: 10100
        title: "REST API"    
    implementer-guide/apis/rest-api/v1:
        position: 10108
        title: "V1"  
    implementer-guide/apis/rest-api/v1/examples:
        title: "Examples"  
    implementer-guide/apis/rest-api/v1/examples/javascript:
        title: "JavaScript"    
    implementer-guide/apis/rest-api/v2:
        position: 10107
        title: "V2"  
    implementer-guide/apis/rest-api/v2/examples:
        title: "Examples"   
    implementer-guide/apis/rest-api/v2/examples/javascript:
        title: "JavaScript" 
    implementer-guide/apis/rest-api/v2/examples/csharp:
        title: "C#"   
    knowledge-base:
        position: 10
        title: "Knowledge Base"
    dotnet-docs:
        position: 130
        title: "Report Server for .NET"
    dotnet-docs/coming-soon:
        position: 130
        title: "Coming soon..."

## Assign layout and category per different paths
## defaults:
## -
##     scope:
##         path: ""
##     values:
##         description_suffix: "Learn more in Telerik Report Server Documentation!"
## -
##     scope:
##         path: "user-guide"
##     values:
##         title_prefix: "User Guide"
##         title_prefix_separator: " - "
## -
##     scope:
##         path: "implementer-guide"
##     values:
##         title_prefix: "Implementer Guide"
##         title_prefix_separator: " - "

## The application virtual path
baseurl: /report-server

## The product name
productName: "Report Server"

## Progress NPM Registry
registry_url: 'https://registry.npm.telerik.com/'

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "report-server"
        editable: true

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Feedback Form Product code
productCode: REPSERVER

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:dikfyfm1qqw'
#google_custom_kb_search: '001595215763381649090:fkoi6yohnf0'
gcs_api_key: 'AIzaSyDNYtM2t6kQtudXwrkft8fSt0PaDxAyxx4'

edit_repo_url: https://github.com/telerik/report-server-docs/edit/master
product: "Telerik Report Server"
product_url: https://www.telerik.com/report-server
platform: report-server
download: http://www.telerik.com/download/report-server
nav:
  "Demos": https://demos.telerik.com/report-server/
  "Release History": https://www.telerik.com/support/whats-new/report-server/release-history
  "About": http://www.telerik.com/report-server
  "Pricing": http://www.telerik.com/purchase/report-server

footer:
-
  title: "Getting Started"
  links:
    "Install Now": http://www.telerik.com/download/report-server
    "Demos": https://demos.telerik.com/report-server/
-
  title: "Support Resources"
  links: 
    "Contact Support": https://www.telerik.com/account/support-tickets
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/report-server
    "Blogs": http://www.telerik.com/blogs/tag/report-server
    "Feedback Portal": https://feedback.telerik.com/Project/171
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 
    
# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
